// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TJConnector.Postgres;

#nullable disable

namespace TJConnector.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250121041256_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TJConnector.Postgres.Entities.CodeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ExternalGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RecordDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusHistory")
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("User")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.ToTable("CodeOrders");
                });

            modelBuilder.Entity("TJConnector.Postgres.Entities.CodeOrderContent", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("CodeOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("DownloadHistory")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("RecordDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CodeOrderId")
                        .IsUnique();

                    b.ToTable("CodeOrdersContents");
                });

            modelBuilder.Entity("TJConnector.Postgres.Entities.Factory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ExternalUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Factories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExternalUid = new Guid("326e5c13-4280-4078-be01-ebed9d73716a"),
                            Name = "DefaulFactory"
                        });
                });

            modelBuilder.Entity("TJConnector.Postgres.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ExternalUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExternalUid = new Guid("d4ee03fa-497e-4228-8db4-505c13e6b3bb"),
                            Name = "DefaulLocation"
                        });
                });

            modelBuilder.Entity("TJConnector.Postgres.Entities.MarkingLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ExternalUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MarkingLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExternalUid = new Guid("0e3cf053-078c-44a7-a198-74cb4d66caf4"),
                            Name = "DefaulMarkingLine"
                        });
                });

            modelBuilder.Entity("TJConnector.Postgres.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AggregationGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ContentApplicationGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("PackageRequestId")
                        .HasColumnType("integer");

                    b.Property<int?>("PackageRequestId1")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RecordDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("SSCCCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusHistory")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PackageRequestId");

                    b.HasIndex("PackageRequestId1");

                    b.HasIndex("SSCCCode")
                        .IsUnique();

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("TJConnector.Postgres.Entities.PackageRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Filename")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("RecordDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusHistory")
                        .HasColumnType("jsonb");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("PackageRequests");
                });

            modelBuilder.Entity("TJConnector.Postgres.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ExternalUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Gtin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("RecordDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TJConnector.Postgres.Entities.CodeOrder", b =>
                {
                    b.HasOne("TJConnector.Postgres.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TJConnector.Postgres.Entities.Product", "Product")
                        .WithMany("CodeOrders")
                        .HasForeignKey("ProductId1");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TJConnector.Postgres.Entities.CodeOrderContent", b =>
                {
                    b.HasOne("TJConnector.Postgres.Entities.CodeOrder", "CodeOrder")
                        .WithOne("Content")
                        .HasForeignKey("TJConnector.Postgres.Entities.CodeOrderContent", "CodeOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TJConnector.Postgres.Entities.CodeOrder", null)
                        .WithOne()
                        .HasForeignKey("TJConnector.Postgres.Entities.CodeOrderContent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeOrder");
                });

            modelBuilder.Entity("TJConnector.Postgres.Entities.Package", b =>
                {
                    b.HasOne("TJConnector.Postgres.Entities.PackageRequest", null)
                        .WithMany()
                        .HasForeignKey("PackageRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TJConnector.Postgres.Entities.PackageRequest", "PackageRequest")
                        .WithMany("Packages")
                        .HasForeignKey("PackageRequestId1");

                    b.Navigation("PackageRequest");
                });

            modelBuilder.Entity("TJConnector.Postgres.Entities.CodeOrder", b =>
                {
                    b.Navigation("Content");
                });

            modelBuilder.Entity("TJConnector.Postgres.Entities.PackageRequest", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("TJConnector.Postgres.Entities.Product", b =>
                {
                    b.Navigation("CodeOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
